### ISSUE TITLE
在创建数据库时报错

### ISSUE THREAD

**Issue by DINOREXNB** [secretflow/scql#19]
使用macOS，没有对原文件做任何修改，退出后重新进入出现错误，请问当出现如下报错该如何解决：
```
(base) [root@5a3ddd566468 dev]# ./scdbclient prompt --host=http://host.docker.internal:8080 --usersConfFileName=examples/docker-compose/client/users.json --sync
> switch root
root> show databases;
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7f4563]

goroutine 1 [running]:
main.runSql({0x0, 0x0}, {0xc000026470, 0xe}, 0xc56aa0, 0x1)
	/home/admin/dev/cmd/scdbclient/main.go:299 +0x483
main.executor({0xc000026470?, 0xf?})
	/home/admin/dev/cmd/scdbclient/main.go:179 +0x1f0
main.runPromptMode()
	/home/admin/dev/cmd/scdbclient/main.go:244 +0x150
main.glob..func3(0xc4ff60?, {0x8c1cdb?, 0x3?, 0x3?})
	/home/admin/dev/cmd/scdbclient/main.go:87 +0x17
github.com/spf13/cobra.(*Command).execute(0xc4ff60, {0xc000195d70, 0x3, 0x3})
	/usr/local/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc4f9a0)
	/usr/local/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/usr/local/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/home/admin/dev/cmd/scdbclient/main.go:348 +0x25
```

**Comment by tongke6** [comment]
@DINOREXNB 你好，请问这个问题可以复现吗？如果可以复现，麻烦在评论里描述下复现步骤，越详细对我们解决问题的帮助越大，谢谢^_^

**Comment by DINOREXNB** [comment]
## 尝试重新搭建
1. 删除docker中的docker-compose与scql
2. 执行：
## start dev container
docker run -d -it --name scql-dev-$(whoami) \
         --mount type=bind,source="$(pwd)",target=/home/admin/dev/ \
         -w /home/admin/dev \
         --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
         --cap-add=NET_ADMIN \
         --privileged=true \
         secretflow/scql-ci:latest

## attach to dev container
docker exec -it scql-dev-$(whoami) bash
Last login: Sat Apr  8 17:13:17 on ttys000
woodways@outekiMacBook-Pro ~ % cd /Users/woodways/Desktop/scql 
woodways@outekiMacBook-Pro scql % docker run -d -it --name scql-dev-$(whoami) \
         --mount type=bind,source="$(pwd)",target=/home/admin/dev/ \
         -w /home/admin/dev \
         --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
         --cap-add=NET_ADMIN \
         --privileged=true \
         secretflow/scql-ci:latest
0dc72fc19595cb0bc93dab738c66b06ef765547d2c2dbc6e88eb3b3051a95add
woodways@outekiMacBook-Pro scql % docker exec -it scql-dev-$(whoami) bash
(base) [root@0dc72fc19595 dev]# go build -o scdbclient cmd/scdbclient/main.go
go: downloading github.com/influxdata/go-prompt v0.2.8
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/spf13/cobra v1.6.1
go: downloading github.com/golang/mock v1.6.0
go: downloading google.golang.org/protobuf v1.28.1
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading github.com/spf13/pflag v1.0.5
go: downloading golang.org/x/sys v0.5.0
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading github.com/pkg/term v1.2.0-beta.2
(base) [root@0dc72fc19595 dev]# sh examples/docker-compose/register.sh
success register user and engine information
(base) [root@0dc72fc19595 docker-compose]# exit
exit
woodways@outekiMacBook-Pro scql % cd examples/docker-compose
woodways@outekiMacBook-Pro docker-compose % docker compose up -d
[+] Running 5/5
 ⠿ Network docker-compose_default           Created                        0.1s
 ⠿ Container docker-compose-engine_alice-1  Started                        1.4s
 ⠿ Container docker-compose-engine_bob-1    Started                        1.2s
 ⠿ Container docker-compose-scdb-1          Started                        1.3s
 ⠿ Container docker-compose-mysql-1         Started                        1.1s
woodways@outekiMacBook-Pro docker-compose % docker exec -it scql-dev-$(whoami) bash
(base) [root@0dc72fc19595 dev]# ./scdbclient prompt --host=http://host.docker.internal:8080 --usersConfFileName=examples/docker-compose/client/users.json --sync
> switch root
root> show databases;
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7f4563]
goroutine 1 [running]:
main.runSql({0x0, 0x0}, {0xc0001a8a00, 0xe}, 0xc56aa0, 0x1)
	/home/admin/dev/cmd/scdbclient/main.go:299 +0x483
main.executor({0xc0001a8a00?, 0xf?})
	/home/admin/dev/cmd/scdbclient/main.go:179 +0x1f0
main.runPromptMode()
	/home/admin/dev/cmd/scdbclient/main.go:244 +0x150
main.glob..func3(0xc4ff60?, {0x8c1cdb?, 0x3?, 0x3?})
	/home/admin/dev/cmd/scdbclient/main.go:87 +0x17
github.com/spf13/cobra.(*Command).execute(0xc4ff60, {0xc000195d70, 0x3, 0x3})
	/usr/local/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc4f9a0)
	/usr/local/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/usr/local/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/home/admin/dev/cmd/scdbclient/main.go:348 +0x25

**Comment by anakinxc** [comment]
Hi @DINOREXNB 

方便提供一下您 macOS 的版本号和机型吗

**Comment by DINOREXNB** [comment]
版本号：macOS Monterey 12.6.3
机型：MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by jingshi-ant** [comment]
go build -o scdbclient cmd/scdbclient/main.go
sh examples/docker-compose/register.sh
等这些部署的命令不在scql-dev-$(whoami)的container内部执行。这个container只建议在编译ci的时候用

**Comment by tongke6** [comment]
@DINOREXNB 我在 macOS 上没能复现你遇到的问题。

麻烦提供下 scdb 的日志，可以通过在宿主机上 `docker compose logs scdb` 查看日志。

**Comment by DINOREXNB** [comment]
```
2023-04-08 18:53:18 docker-compose-mysql-1         | 2023-04-08 18:53:18+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.32-1.el8 started.
2023-04-08 18:53:18 docker-compose-engine_bob-1    | 2023-04-08 18:53:18.081 [info] [main.cc:main:262] Adding MuxReceiverService into brpc server
2023-04-08 18:53:18 docker-compose-mysql-1         | 2023-04-08 18:53:18+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-04-08 18:53:18 docker-compose-engine_bob-1    | 2023-04-08 18:53:18.084 [info] [main.cc:BuildRouter:147] Building EmbedRouter from json conf
2023-04-08 18:53:18 docker-compose-engine_bob-1    | 2023-04-08 18:53:18.086 [info] [thread_pool.cc:ThreadPool:30] Create a fixed thread pool with size 4
2023-04-08 18:53:18 docker-compose-engine_bob-1    | 2023-04-08 18:53:18.087 [info] [main.cc:main:283] Adding EngineService into brpc server
2023-04-08 18:53:18 docker-compose-mysql-1         | 2023-04-08 18:53:18+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.32-1.el8 started.
2023-04-08 18:53:18 docker-compose-mysql-1         | 2023-04-08 18:53:18+08:00 [Note] [Entrypoint]: Initializing database files
2023-04-08 18:53:18 docker-compose-mysql-1         | 2023-04-08T10:53:18.678987Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
2023-04-08 18:53:18 docker-compose-mysql-1         | 2023-04-08T10:53:18.679133Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.32) initializing of server in progress as process 79
2023-04-08 18:53:18 docker-compose-mysql-1         | 2023-04-08T10:53:18.688917Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2023-04-08 18:53:19 docker-compose-mysql-1         | 2023-04-08T10:53:19.206799Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2023-04-08 18:53:20 docker-compose-mysql-1         | 2023-04-08T10:53:20.843328Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2023-04-08 18:53:24 docker-compose-mysql-1         | 2023-04-08 18:53:24+08:00 [Note] [Entrypoint]: Database files initialized
2023-04-08 18:53:24 docker-compose-mysql-1         | 2023-04-08 18:53:24+08:00 [Note] [Entrypoint]: Starting temporary server
2023-04-08 18:53:25 docker-compose-mysql-1         | 2023-04-08T10:53:24.988415Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
2023-04-08 18:53:25 docker-compose-mysql-1         | 2023-04-08T10:53:24.990241Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.32) starting as process 124
2023-04-08 18:53:25 docker-compose-mysql-1         | 2023-04-08T10:53:25.014546Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2023-04-08 18:53:25 docker-compose-mysql-1         | 2023-04-08T10:53:25.155751Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2023-04-08 18:53:25 docker-compose-mysql-1         | 2023-04-08T10:53:25.424641Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2023-04-08 18:53:25 docker-compose-mysql-1         | 2023-04-08T10:53:25.424796Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2023-04-08 18:53:25 docker-compose-mysql-1         | 2023-04-08T10:53:25.427802Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2023-04-08 18:53:25 docker-compose-mysql-1         | 2023-04-08T10:53:25.453215Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
2023-04-08 18:53:25 docker-compose-mysql-1         | 2023-04-08T10:53:25.453425Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.32'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
2023-04-08 18:53:25 docker-compose-mysql-1         | 2023-04-08 18:53:25+08:00 [Note] [Entrypoint]: Temporary server started.
2023-04-08 18:53:25 docker-compose-mysql-1         | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
2023-04-08 18:53:26 docker-compose-mysql-1         | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
2023-04-08 18:53:26 docker-compose-mysql-1         | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
2023-04-08 18:53:26 docker-compose-mysql-1         | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
2023-04-08 18:53:29 docker-compose-mysql-1         | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
2023-04-08 18:53:29 docker-compose-mysql-1         | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
2023-04-08 18:53:29 docker-compose-mysql-1         | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
2023-04-08 18:53:29 docker-compose-mysql-1         | 
2023-04-08 18:53:29 docker-compose-mysql-1         | 2023-04-08 18:53:29+08:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/alice_init.sql
2023-04-08 18:53:29 docker-compose-mysql-1         | 
2023-04-08 18:53:29 docker-compose-mysql-1         | 
2023-04-08 18:53:29 docker-compose-mysql-1         | 2023-04-08 18:53:29+08:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/bob_init.sql
2023-04-08 18:53:29 docker-compose-mysql-1         | 
2023-04-08 18:53:29 docker-compose-mysql-1         | 
2023-04-08 18:53:29 docker-compose-mysql-1         | 2023-04-08 18:53:29+08:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/scdb_init.sql
2023-04-08 18:53:30 docker-compose-mysql-1         | 
2023-04-08 18:53:30 docker-compose-mysql-1         | 
2023-04-08 18:53:30 docker-compose-mysql-1         | 2023-04-08 18:53:30+08:00 [Note] [Entrypoint]: Stopping temporary server
2023-04-08 18:53:30 docker-compose-mysql-1         | 2023-04-08T10:53:30.090071Z 13 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.32).
2023-04-08 18:53:31 docker-compose-mysql-1         | 2023-04-08T10:53:31.139218Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.32)  MySQL Community Server - GPL.
2023-04-08 18:53:32 docker-compose-mysql-1         | 2023-04-08 18:53:32+08:00 [Note] [Entrypoint]: Temporary server stopped
2023-04-08 18:53:32 docker-compose-mysql-1         | 
2023-04-08 18:53:32 docker-compose-mysql-1         | 2023-04-08 18:53:32+08:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
2023-04-08 18:53:18 docker-compose-engine_bob-1    | 2023-04-08 18:53:18.089 [info] [session_manager.cc:WatchSessionTimeoutThread:158] WatchSessionTimeoutThread startup, session default timeout=1800s
2023-04-08 18:53:18 docker-compose-engine_bob-1    | 2023-04-08 18:53:18.091 [warning] [server.cpp:BRPC:1113] Builtin services are disabled according to ServerOptions.has_builtin_services
2023-04-08 18:53:18 docker-compose-engine_bob-1    | 2023-04-08 18:53:18.092 [info] [main.cc:main:297] Started engine rpc server success, listen on: 0.0.0.0:8003
2023-04-09 00:11:21 docker-compose-engine_bob-1    | *** SIGTERM received at time=1680970281 on cpu 1 ***
2023-04-09 00:11:21 docker-compose-engine_bob-1    | PC: @     0x7f4d278fa658  (unknown)  nanosleep
2023-04-09 00:11:21 docker-compose-engine_bob-1    |     @     0x7f4d28012ce0  (unknown)  (unknown)
2023-04-08 18:53:32 docker-compose-mysql-1         | 
2023-04-08 18:53:32 docker-compose-mysql-1         | 2023-04-08T10:53:32.377865Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
2023-04-08 18:53:32 docker-compose-mysql-1         | 2023-04-08T10:53:32.379590Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.32) starting as process 1
2023-04-08 18:53:32 docker-compose-mysql-1         | 2023-04-08T10:53:32.388414Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2023-04-08 18:53:32 docker-compose-mysql-1         | 2023-04-08T10:53:32.532524Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2023-04-08 18:53:32 docker-compose-mysql-1         | 2023-04-08T10:53:32.791830Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2023-04-08 18:53:32 docker-compose-mysql-1         | 2023-04-08T10:53:32.791905Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2023-04-08 18:53:32 docker-compose-mysql-1         | 2023-04-08T10:53:32.793740Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2023-04-08 18:53:32 docker-compose-mysql-1         | 2023-04-08T10:53:32.821001Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2023-04-08 18:53:32 docker-compose-mysql-1         | 2023-04-08T10:53:32.821127Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.32'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
2023-04-09 00:11:21 docker-compose-mysql-1         | 2023-04-08T16:11:21.686549Z 0 [System] [MY-013172] [Server] Received SHUTDOWN from user <via user signal>. Shutting down mysqld (Version: 8.0.32).
2023-04-09 00:11:22 docker-compose-mysql-1         | 2023-04-08T16:11:22.954517Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.32)  MySQL Community Server - GPL.
2023-04-08 18:53:18 docker-compose-scdb-1          | 2023-04-08 18:53:18.486 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-08 18:53:18 docker-compose-scdb-1          | 2023-04-08 18:53:18.486 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-08 18:53:18 docker-compose-scdb-1          | 2023-04-08 18:53:18.486 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
2023-04-08 18:53:18 docker-compose-scdb-1          | [error] failed to initialize database, got error dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:18 docker-compose-scdb-1          | 2023-04-08 18:53:18.486 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:18 docker-compose-scdb-1          | 2023-04-08 18:53:18.486 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-08 18:53:18 docker-compose-scdb-1          | 2023-04-08 18:53:18.486 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-08 18:53:18 docker-compose-scdb-1          | 2023-04-08 18:53:18.486 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
2023-04-08 18:53:18 docker-compose-scdb-1          | [error] failed to initialize database, got error dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:18 docker-compose-scdb-1          | 2023-04-08 18:53:18.486 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:19 docker-compose-scdb-1          | 2023-04-08 18:53:19.486 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-08 18:53:19 docker-compose-scdb-1          | 2023-04-08 18:53:19.486 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-08 18:53:19 docker-compose-scdb-1          | 2023-04-08 18:53:19.486 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
2023-04-08 18:53:19 docker-compose-scdb-1          | [error] failed to initialize database, got error dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:19 docker-compose-scdb-1          | 2023-04-08 18:53:19.486 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:20 docker-compose-scdb-1          | 2023-04-08 18:53:20.486 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-08 18:53:20 docker-compose-scdb-1          | 2023-04-08 18:53:20.486 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-08 18:53:20 docker-compose-scdb-1          | 2023-04-08 18:53:20.486 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
2023-04-08 18:53:20 docker-compose-scdb-1          | [error] failed to initialize database, got error dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:20 docker-compose-scdb-1          | 2023-04-08 18:53:20.486 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:21 docker-compose-scdb-1          | 2023-04-08 18:53:21.486 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-08 18:53:21 docker-compose-scdb-1          | 2023-04-08 18:53:21.486 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-08 18:53:21 docker-compose-scdb-1          | 2023-04-08 18:53:21.486 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
2023-04-08 18:53:21 docker-compose-scdb-1          | [error] failed to initialize database, got error dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:21 docker-compose-scdb-1          | 2023-04-08 18:53:21.486 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:23 docker-compose-scdb-1          | 2023-04-08 18:53:23.486 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-08 18:53:23 docker-compose-scdb-1          | 2023-04-08 18:53:23.486 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-08 18:53:23 docker-compose-scdb-1          | 2023-04-08 18:53:23.486 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
2023-04-08 18:53:23 docker-compose-scdb-1          | [error] failed to initialize database, got error dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:23 docker-compose-scdb-1          | 2023-04-08 18:53:23.486 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:27 docker-compose-scdb-1          | 2023-04-08 18:53:27.486 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-08 18:53:27 docker-compose-scdb-1          | 2023-04-08 18:53:27.486 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-08 18:53:27 docker-compose-scdb-1          | 2023-04-08 18:53:27.486 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
2023-04-08 18:53:27 docker-compose-scdb-1          | [error] failed to initialize database, got error dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:27 docker-compose-scdb-1          | 2023-04-08 18:53:27.486 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.21.0.5:3306: connect: connection refused
2023-04-08 18:53:34 docker-compose-scdb-1          | 2023-04-08 18:53:34.486 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-08 18:53:34 docker-compose-scdb-1          | 2023-04-08 18:53:34.486 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-08 18:53:34 docker-compose-scdb-1          | 2023-04-08 18:53:34.486 INFO main.go:122 Starting to serve request with http...
2023-04-08 18:53:18 docker-compose-engine_alice-1  | 2023-04-08 18:53:18.002 [info] [main.cc:main:262] Adding MuxReceiverService into brpc server
2023-04-08 18:53:18 docker-compose-engine_alice-1  | 2023-04-08 18:53:18.012 [info] [main.cc:BuildRouter:147] Building EmbedRouter from json conf
2023-04-08 18:53:18 docker-compose-engine_alice-1  | 2023-04-08 18:53:18.015 [info] [thread_pool.cc:ThreadPool:30] Create a fixed thread pool with size 4
2023-04-08 18:53:18 docker-compose-engine_alice-1  | 2023-04-08 18:53:18.018 [info] [main.cc:main:283] Adding EngineService into brpc server
2023-04-08 18:53:18 docker-compose-engine_alice-1  | 2023-04-08 18:53:18.018 [info] [session_manager.cc:WatchSessionTimeoutThread:158] WatchSessionTimeoutThread startup, session default timeout=1800s
2023-04-08 18:53:18 docker-compose-engine_alice-1  | 2023-04-08 18:53:18.022 [warning] [server.cpp:BRPC:1113] Builtin services are disabled according to ServerOptions.has_builtin_services
2023-04-08 18:53:18 docker-compose-engine_alice-1  | 2023-04-08 18:53:18.023 [info] [main.cc:main:297] Started engine rpc server success, listen on: 0.0.0.0:8003
```

**Comment by DINOREXNB** [comment]
```
2023-04-10 22:43:21.41010 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-10 22:43:21.41010 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-10 22:43:21.41010 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
[error] failed to initialize database, got error dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:21.41010 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:21.41010 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-10 22:43:21.41010 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-10 22:43:21.41010 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
[error] failed to initialize database, got error dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:21.41010 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:22.41010 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-10 22:43:22.41010 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-10 22:43:22.41010 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
[error] failed to initialize database, got error dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:22.41010 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:23.41010 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-10 22:43:23.41010 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-10 22:43:23.41010 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
[error] failed to initialize database, got error dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:23.41010 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:24.41010 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-10 22:43:24.41010 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-10 22:43:24.41010 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
[error] failed to initialize database, got error dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:24.41010 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:26.41010 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-10 22:43:26.41010 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-10 22:43:26.41010 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
[error] failed to initialize database, got error dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:26.41010 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:30.41010 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-10 22:43:30.41010 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-10 22:43:30.41010 INFO logger.go:147 /home/admin/dev/pkg/scdb/server/server.go:97
[error] failed to initialize database, got error dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:30.41010 FATAL main.go:102 Failed to connect to database and bootstrap it: dial tcp 172.22.0.3:3306: connect: connection refused
2023-04-10 22:43:37.41010 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-10 22:43:37.41010 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-10 22:43:37.41010 INFO main.go:122 Starting to serve request with http...
2023-04-10 22:45:25.41010 INFO main.go:85 Starting to read config file: /home/admin/configs/config.yml
2023-04-10 22:45:25.41010 INFO main.go:98 Starting to connect to database and do bootstrap if necessary...
2023-04-10 22:45:25.41010 INFO main.go:122 Starting to serve request with http...
```

**Comment by tongke6** [comment]
@DINOREXNB 您好，上面的日志是在 scdbclient panic 之后查看的吗？目前从该日志上看不出什么异常。

麻烦尝试下从 #20 PR 里构建 scdbclient，试下此问题是否还存在

**Comment by tongke6** [comment]
update，#20 已合入 main 分支，可以 pull 最新的代码构建试一下

**Comment by DINOREXNB** [comment]
感谢，问题已解决
